"use client";

import Link from "next/link";
import { motion } from "framer-motion";

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-white">
    <motion.main
      initial={{ opacity: 0, y: 12 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.5, ease: [0.16, 1, 0.3, 1] }}
      className="max-w-3xl mx-auto py-16 px-4"
    >
      <Link
        href="/"
        className="btn-primary-light text-sm py-2 px-4 inline-flex items-center mb-8 "
      >
        Back
      </Link>

     
        <h1 className="text-3xl font-semibold text-dark tracking-tight mb-2">
          Terms of Service
        </h1>
        <p className="text-dark-secondary text-sm mb-8">
          Effective date: [insert date before publishing] · Last updated: [insert date]
        </p>

        <div className="space-y-8 text-black/70 text-sm leading-relaxed">
          <p>
            These Terms of Service (&quot;Terms&quot;) govern your access to and use of Pible&apos;s web
            dashboard, CLI, browser extension, and VS Code extension (together, the
            &quot;Service&quot;). By creating an account or otherwise using the Service, you agree to
            these Terms. If you don&apos;t agree, please don&apos;t use the Service.
          </p>

          <section>
            <h2 className="text-lg font-semibold text-black mt-8 mb-3">1. What Pible is</h2>
            <p>
              Pible is a continuity and intelligence layer for AI-assisted software development.
              It stores your project&apos;s structure, decisions, tasks, and history so that
              different AI coding agents can pick up work where a previous one left off. Pible is
              not itself an AI coding agent, and it does not write code on your behalf.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-black mt-8 mb-3">2. Accounts</h2>
            <ul className="list-disc list-inside space-y-1 text-black/60">
              <li>You sign in via GitHub or Google OAuth — there is no separate username/password account.</li>
              <li>You&apos;re responsible for maintaining the security of the GitHub/Google account you use to sign in, and for any activity that happens under your Pible account as a result.</li>
              <li>You must provide accurate information and keep it up to date where the Service asks you to.</li>
              <li>You may not share your account or API keys with anyone not authorized to act on your behalf, and you&apos;re responsible for activity performed with your API keys until you revoke them.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-black mt-8 mb-3">3. Acceptable use</h2>
            <p>You agree not to:</p>
            <ul className="list-disc list-inside mt-2 space-y-1 text-black/60">
              <li>Use the Service to store or process content you don&apos;t have the right to store or process</li>
              <li>Attempt to gain unauthorized access to another user&apos;s projects, accounts, or API keys</li>
              <li>Reverse-engineer, decompile, or attempt to extract the source code of the Service, except where applicable law permits it</li>
              <li>Use the Service to build a directly competing product using data or access obtained through the Service</li>
              <li>Interfere with or disrupt the integrity or performance of the Service (e.g. abusive automated requests, attempts to bypass API-key scoping)</li>
              <li>Use the Service for any unlawful purpose</li>
            </ul>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-black mt-8 mb-3">4. Your content</h2>
            <ul className="list-disc list-inside space-y-1 text-black/60">
              <li>You retain ownership of everything you or your connected AI agents submit to Pible — project metadata, decisions, tasks, task run records, and issues (&quot;Your Content&quot;).</li>
              <li>You grant Pible a limited license to store, process, and display Your Content solely to operate and improve the Service (e.g. compiling context packages, rendering your dashboard).</li>
              <li>As described in our <Link href="/privacy" className="underline text-black/80 hover:text-black">Privacy Policy</Link>, Pible does not store your source code or full file contents — only project structure, decisions, and summaries.</li>
              <li>You&apos;re responsible for having the necessary rights to any content you submit, including content generated by third-party AI agents you connect to the Service.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-black mt-8 mb-3">5. AI agents &amp; third-party tools</h2>
            <p>
              Pible is designed to work alongside third-party AI coding agents (such as Claude
              Code, Cursor, or Kiro) that you choose to connect. We don&apos;t control the behavior,
              output, or accuracy of these third-party agents, and we&apos;re not responsible for
              actions they take in your codebase. Task statuses and run records reported by an
              agent (e.g. &quot;completed&quot;) reflect what the agent claimed — where our Verification
              Engine is enabled, these claims may be checked against actual build/test results, but
              you remain responsible for reviewing and approving changes to your own project.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-black mt-8 mb-3">6. The local <code className="text-black/80 bg-black/5 px-1.5 py-0.5 rounded text-xs">.pible/</code> folder</h2>
            <p>
              The CLI writes a human-readable mirror of your project state into a{" "}
              <code className="text-black/80 bg-black/5 px-1.5 py-0.5 rounded text-xs">.pible/</code>{" "}
              folder inside your own repository. That folder is part of your repository, subject to
              your own repository&apos;s license, visibility, and access controls — not Pible&apos;s. We&apos;re
              not responsible for how that folder is stored, shared, or distributed once it&apos;s part
              of your repo.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-black mt-8 mb-3">7. Fees</h2>
            <p>
              [Insert pricing details once finalized — e.g. free tier limits, paid plan terms,
              billing cycle, refund policy. If Pible is free during this phase, state that plainly
              and note that pricing may be introduced with advance notice.]
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-black mt-8 mb-3">8. Termination</h2>
            <ul className="list-disc list-inside space-y-1 text-black/60">
              <li>You may stop using the Service and delete your account at any time from the dashboard.</li>
              <li>We may suspend or terminate your access if you violate these Terms, misuse the Service, or if required by law.</li>
              <li>On termination, Section 5 of our Privacy Policy governs what happens to your data.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-black mt-8 mb-3">9. Disclaimers</h2>
            <p>
              The Service is provided &quot;as is&quot; and &quot;as available,&quot; without warranties of any
              kind, express or implied. We don&apos;t guarantee that the Service will be
              uninterrupted, error-free, or that context packages, task statuses, or agent
              performance metrics will be complete or accurate — Pible reflects what agents and
              users report to it, and can only verify what the Verification Engine is configured to
              check.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-black mt-8 mb-3">10. Limitation of liability</h2>
            <p>
              To the maximum extent permitted by law, Pible and its team won&apos;t be liable for any
              indirect, incidental, special, or consequential damages, or for any loss of data,
              revenue, or profits, arising from your use of the Service — including actions taken
              by third-party AI agents connected through the Service.
              [This section should be reviewed and tightened by a lawyer before publishing —
              liability limitations are jurisdiction-dependent and often need specific statutory
              language to be enforceable.]
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-black mt-8 mb-3">11. Changes to these Terms</h2>
            <p>
              We may update these Terms as the Service evolves. We&apos;ll notify you of material
              changes via the dashboard or email before they take effect. Continued use of the
              Service after changes take effect means you accept the updated Terms.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-black mt-8 mb-3">12. Governing law</h2>
            <p>
              [Insert the governing jurisdiction — e.g. &quot;These Terms are governed by the laws of
              [state/country], without regard to conflict-of-law principles.&quot; This should match
              where your business is legally established.]
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-black mt-8 mb-3">13. Contact</h2>
            <p>
              Questions about these Terms? Reach us at [insert contact email] or [insert
              company/individual name and address if legally required in your jurisdiction].
            </p>
          </section>
        </div>

    </motion.main>
    </div>
  );
}